# fly.toml app configuration file generated for discordmusicbot-k-zztq on 2026-10-03T23:44:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discordmusicbot-k-zztq'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
